### ISSUE TITLE
assignCoordinates is unsafe pattern matching.

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL23/solver-tricktractreat#5]
Solution 1: have it take `[[Maybe Player]] -> `, then instead of isOngoing you should pattern match.

Solution 2: Why turn things into coordinates, instead of just looking nicely through the lists.

```Haskell
findNothingIdx :: [Maybe a] -> [Int]
openSpaces board :: [[Maybe Player]] = 
     concat [allPairs i (findNothingIdx row) | (i,row) <- zip [1..] board]
allPairs :: a -> [b] -> [(a,b)]
```

**Comment by JorgeFLarach** [comment]
Replaced `findLegalSubBoardMoves` and `assignCoordinates` with functions specified above
