### ISSUE TITLE
findLegalMoves refactoring

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL23/solver-tricktractreat#6]
Refactor the findLegalMoves for Nothing case by first  compute the list of `(coord, subboard)` tuples and then mapping `makeBigMove $ (coord, findLegalSubBoardMoves subBoard)` over it. 

Possibly even better, have a helper function that takes a row and an index, and concat those together.

**Comment by JorgeFLarach** [comment]
Implemented the second suggestion
